### ISSUE TITLE
An unexpected error has occurred when selecting 2ª Dose in Percentagem da população vacinada por faixa etária

### ISSUE THREAD

**Issue by dfrazao** [alicescfernandes/mapa-vacinacao-c19#14]
When selecting selecting 2ª Dose in Percentagem da população vacinada por faixa etária, the page presents this error:
![image](https://user-images.githubusercontent.com/26813660/122640915-e3126600-d0f9-11eb-894c-c0b345ff1ad8.png)
This is the console output: 
![image](https://user-images.githubusercontent.com/26813660/122640894-c70ec480-d0f9-11eb-8fcf-6399caa6e958.png)

**Comment by alicescfernandes** [comment]
Hi!
Thanks for the report!
It should be fixed on the next deploy
