### ISSUE TITLE
What backs up your claim that Portugal needs 56.78% to have herd immunity?

### ISSUE THREAD

**Issue by chaimite** [alicescfernandes/mapa-vacinacao-c19#2]

**Comment by alicescfernandes** [comment]
Hi. This is purely based on data. I know what's the population, and i also know what's the know many people were vaccinated. [With the estimates given on this article](https://rr.sapo.pt/2020/08/24/pais/coronavirus-70-das-pessoas-imunizadas-sera-suficiente-para-criar-imunidade-de-grupo/noticia/204533/) (from a newspaper) which is an organisation that is managed by our health services, and on this article they say that to achieve herd immunity, we would have to get between 60% ad 70% of the people vaccinated. Based on what i explained above, i can make some assumptions on the herd immunity. I was originaly aiming at 60%.

However, most articles and news websites make those calculations with a value of 70%, so i changed as well to 70% to make sure that all sources use the same math, to not cause any confusion.

This annotation is also described in the "Notas" section on the bottom of the webpage. If you are curious enough, you can check out [here](https://github.com/alicescfernandes/mapa-vacinacao-c19/blob/75538640d2354166426a090912a013784403f608/pages/index.js#L86) or [here](https://github.com/alicescfernandes/mapa-vacinacao-c19/blob/75538640d2354166426a090912a013784403f608/pages/index.js#L184) line of code (where i do the math)

**Comment by chaimite** [comment]
I have always read that it required 70%. That's why it was a bit strange when I saw 50 something percent. Makes sense now
