### ISSUE TITLE
Fully vaccinated rate does not match the DGS rate

### ISSUE THREAD

**Issue by luist18** [alicescfernandes/mapa-vacinacao-c19#22]
In the vacinas.csv in dssg-pt repository, there is a field for fully vaccinated people that matches the DGS rate (pessoas_vacinadas_completamente). That number should be used to calculate the rate instead of the number of 2nd doses.

**Comment by alicescfernandes** [comment]
Hi. I'm not currently using the values from DSSG-PT because (sometimes) they can take a while to be updated. However I'm still trying to find a way to calculate the values on "our" side. Still haven't figured out a solution

**Comment by luist18** [comment]
As far as I understood dssg updates every Tuesday, with the vaccination report, the number of people totally vaccinated. During the next week, they update that number by increasing it with the number of 2nd doses given in a day. After the week is passed they update again with the Tuesday report in order to match with the unidoses shots.

**Comment by alicescfernandes** [comment]
So far it's what i've seen from their code. It should be easy to do the math with the already avaliable data

**Comment by alicescfernandes** [comment]
@luist18 you shoul now be able to see the correct number in https://next.vacinacaocovid19.pt/
