### ISSUE TITLE
Application error: a client-side exception has occurred (developer guidance)

### ISSUE THREAD

**Issue by gsaponaro** [alicescfernandes/mapa-vacinacao-c19#27]
Olá @alicescfernandes 

Assinalo que a página https://www.vacinacaocovid19.pt/ mostra o erro Application error: a client-side exception has occurred (developer guidance).

**Comment by alicescfernandes** [comment]
Olá.
Obrigado pelo o reporte.

Nós vamos buscar os dados às dssg-pt e o que aconteceu foi que algumas colunas mudaram de nome, e como estes dados são verificados e testados por eles, normalmente não validarmos e são atualizados automaticamente. Suspeito que isto já está assim ou desde ontem ou terça que passou e nem me apercebi

Já está resolvido!
