### ISSUE TITLE
Add link to twitter on home alert div

### ISSUE THREAD

**Issue by chaimite** [alicescfernandes/mapa-vacinacao-c19#4]
On your home alert div you have: "....segue-nos no twitter..."
You could put an external link on the twitter part for users to go to twitter, I imagine you already can redirect users from twitter to the website.
Edit: Just saw you have it on the side. But I would still put it there on the word twitter.

**Comment by alicescfernandes** [comment]
Hi. Sorry, totally missed this one. The alert is now gone, but will keep that in mind when putting the alert again
